// Mocks generated by Mockito 5.4.4 from annotations
// in todolist/test/data/repositories/user/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todolist/data/datasource/task/task_datasource_proxy.dart'
    as _i7;
import 'package:todolist/data/datasource/user/auth_remote_datasource.dart'
    as _i4;
import 'package:todolist/data/models/auth/auth_dto.dart' as _i6;
import 'package:todolist/data/models/task_model.dart' as _i8;
import 'package:todolist/domain/entities/task_entity.dart' as _i3;
import 'package:todolist/domain/entities/user/user_entity.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserEntity_0 extends _i1.SmartFake implements _i2.UserEntity {
  _FakeUserEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskEntity_1 extends _i1.SmartFake implements _i3.TaskEntity {
  _FakeTaskEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i4.AuthRemoteDatasource {
  MockAuthRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserEntity> login(_i6.AuthDTO? auth) => (super.noSuchMethod(
        Invocation.method(
          #login,
          [auth],
        ),
        returnValue: _i5.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #login,
            [auth],
          ),
        )),
      ) as _i5.Future<_i2.UserEntity>);

  @override
  _i5.Future<_i2.UserEntity> signUp(_i6.AuthDTO? auth) => (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [auth],
        ),
        returnValue: _i5.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #signUp,
            [auth],
          ),
        )),
      ) as _i5.Future<_i2.UserEntity>);

  @override
  _i5.Future<_i2.UserEntity> getUser() => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue: _i5.Future<_i2.UserEntity>.value(_FakeUserEntity_0(
          this,
          Invocation.method(
            #getUser,
            [],
          ),
        )),
      ) as _i5.Future<_i2.UserEntity>);

  @override
  _i5.Future<bool> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [TaskDataSourceProxy].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskDataSourceProxy extends _i1.Mock
    implements _i7.TaskDataSourceProxy {
  MockTaskDataSourceProxy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void switchDataSource(bool? online) => super.noSuchMethod(
        Invocation.method(
          #switchDataSource,
          [online],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.TaskEntity> createTask(_i8.TaskModel? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i5.Future<_i3.TaskEntity>.value(_FakeTaskEntity_1(
          this,
          Invocation.method(
            #createTask,
            [task],
          ),
        )),
      ) as _i5.Future<_i3.TaskEntity>);

  @override
  _i5.Future<bool> deleteTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i3.TaskEntity>> getTasks() => (super.noSuchMethod(
        Invocation.method(
          #getTasks,
          [],
        ),
        returnValue: _i5.Future<List<_i3.TaskEntity>>.value(<_i3.TaskEntity>[]),
      ) as _i5.Future<List<_i3.TaskEntity>>);

  @override
  _i5.Future<_i3.TaskEntity> updateTask(_i3.TaskEntity? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i5.Future<_i3.TaskEntity>.value(_FakeTaskEntity_1(
          this,
          Invocation.method(
            #updateTask,
            [task],
          ),
        )),
      ) as _i5.Future<_i3.TaskEntity>);
}
